version: '3.0'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:18.0.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      command:
        - start-dev
        - --features admin-fine-grained-authz
      depends_on:
        - postgres
  mfe-frenchie-store-host:
    build:
      context: ./host-app
    ports:
      - "3000:3000"
    container_name: mfe-frenchie-store-host
    stdin_open: true
  mfe-products:
      build:
        context: ./mf-products
      ports:
        - "3001:3001"
      container_name: mfe-products
      stdin_open: true
  mfe-cart:
    build:
      context: ./mf-cart
    ports:
      - "3002:3002"
    container_name: mfe-cart
    stdin_open: true
  mfe-backend:
    build:
      context: './backend'
    ports:
      - "3003:3003"
    container_name: mfe-frenchie-store-backend